[project]
name = "repl-nix-bayareascenicdrives"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "folium>=0.18.0",
    "streamlit-folium>=0.23.2",
    "streamlit>=1.40.2",
]
